### PR TITLE
Adjust exists subquery for Oracle

### PR DESCRIPTION
**Pull request by ribasushi**
I **believe** this is all that's needed to address https://github.com/frioux/DBIx-Class-Helpers/issues/104. @abraxxa please test when time permits.

### CODE REVIEW

**Comment by abraxxa** [comment]
I tested the changed code and sadly it didn't change the error message.

**Comment by ribasushi** [comment]
> I tested the changed code and sadly it didn't change the error message.

If the error message is exactly the same
  => this means that the query that executed is exactly the same
    => which means the conditional that I added failed
      => which should not be possible

Either you are not testing against the correct code, or there is a secondary bug of some sort lurking somewhere obscuring the correct sqlt_type. You will have to debug this further locally.

**Comment by abraxxa** [comment]
The error message doesn't include the full sql query just the start so it is the same. Yes DBIC_TRACE showed that 'FROM DUAL' has been appended.

Oracle has no 'SELECT EXISTS' as far as I see here: https://docs.oracle.com/database/121/SQLRF/statements_10002.htm#SQLRF01702

I only found 'exists' here https://docs.oracle.com/database/121/SQLRF/conditions013.htm#SQLRF52167

**Comment by ribasushi** [comment]
> Oracle has no 'SELECT EXISTS'

You are mis-interpreting the query we are issuing ( EXISTS is a standalone operator, not a qualifier for SELECT: think `SELECT column1, function2(...), value3` ). You need to try to dig harder and apply more thought.

I can try to setup the CI portion locally, and figure this out, but this is fiddly and I definitely won't be able to look until the weekend or beyond.

**Comment by abraxxa** [comment]
The * in Oracles error messages haven't failed me in the past to point at the correct location of the query and it points at the EXISTS right after SELECT.
As shown in the stackoverflow I've linked to `select count(*) from dual where exists ($subquery)` should be a valid statement.
I don't know EXISTS at all and haven't used it before so can't help but testing queries.

**Comment by ribasushi** [comment]
lack of available expertise, closing until such materializes

**Pull request closed without merging**
